"""Day 6 - Error analysis library.

All business logic for error bucketing, stratified sampling, TSV export,
and figure generation lives here so the CLI script and the notebook both
import from a single, testable source of truth.

Public API
----------
load_predictions(approach_a_path, approach_b_path)  -> (list[dict], list[dict])
extract_spans(tags)                                  -> list[tuple[int, int, str]]
compute_buckets(records)                             -> BucketResult
collect_error_instances(records)                     -> dict[str, list[ErrorInstance]]
stratified_sample(instances, max_total, seed)        -> list[ErrorInstance]
build_tsv_rows(samples, approach_label)              -> list[dict]
save_tsv(rows, path)                                 -> None
plot_error_distribution(a, b, out_path, dpi)         -> matplotlib.figure.Figure
"""

from __future__ import annotations

import csv
import json
import logging
import pathlib
import random
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, TypedDict

logger = logging.getLogger(__name__)

# Constants
_INT_TO_BIO: dict[int, str] = {
    0: "O",
    1: "B-PER",
    2: "I-PER",
    3: "B-EMAIL",
    4: "I-EMAIL",
}

BUCKET_KEYS = ("FN_PER", "FN_EMAIL", "FP_PER", "FP_EMAIL")

TSV_FIELDS = (
    "approach",
    "sentence_idx",
    "tokens",
    "error_type",
    "gold_span",
    "pred_span",
    "sub_label",
    "notes",
)


# Data types
class ErrorInstance(TypedDict):
    sentence_idx: int
    tokens: list[str]
    error_type: str   # one of BUCKET_KEYS
    gold_span: str
    pred_span: str


@dataclass(frozen=True)
class BucketResult:
    FN_PER: int
    FN_EMAIL: int
    FP_PER: int
    FP_EMAIL: int

    @property
    def total_errors(self) -> int:
        return self.FN_PER + self.FN_EMAIL + self.FP_PER + self.FP_EMAIL

    @property
    def pct(self) -> dict[str, float]:
        t = self.total_errors
        if t == 0:
            return {k: 0.0 for k in BUCKET_KEYS}
        return {k: round(getattr(self, k) / t * 100, 2) for k in BUCKET_KEYS}

    def to_dict(self) -> dict[str, Any]:
        return {
            "FN_PER":       self.FN_PER,
            "FN_EMAIL":     self.FN_EMAIL,
            "FP_PER":       self.FP_PER,
            "FP_EMAIL":     self.FP_EMAIL,
            "total_errors": self.total_errors,
            "pct":          self.pct,
        }


# I/O helpers
def _load_jsonl(path: pathlib.Path) -> list[dict]:
    records: list[dict] = []
    with open(path, encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                logger.warning("Skipping malformed JSON at %s line %d: %s", path.name, lineno, exc)
    return records


def _normalise_record(raw: dict, gold_key: str, pred_key: str) -> dict:
    """Return a record with canonical gold_tags / pred_tags keys."""
    return {
        "tokens":    raw.get("tokens", []),
        "gold_tags": raw.get(gold_key, raw.get("gold_tags", [])),
        "pred_tags": raw.get(pred_key, raw.get("pred_tags", [])),
    }


def load_predictions(
    approach_a_path: pathlib.Path,
    approach_b_path: pathlib.Path,
) -> tuple[list[dict], list[dict]]:
    """Load and normalise both prediction files.

    Approach A (encoder):  keys gold_tags / pred_tags
    Approach B (LLM):      keys ner_tags  / predicted_tags
    Raises FileNotFoundError with a clear message if either file is absent.
    """
    missing: list[str] = []
    if not approach_a_path.exists():
        missing.append(
            f"  Approach A: {approach_a_path}\n"
            "  -> generated by Day 5: run scripts/05_evaluate_all.py"
        )
    if not approach_b_path.exists():
        missing.append(
            f"  Approach B: {approach_b_path}\n"
            "  -> generated by Day 4: run scripts/04_llm_inference.py"
        )
    if missing:
        raise FileNotFoundError("Missing prediction file(s):\n" + "\n".join(missing))

    raw_a = _load_jsonl(approach_a_path)
    records_a = [_normalise_record(r, "gold_tags", "pred_tags") for r in raw_a]
    logger.info("Loaded %d Approach A records from %s", len(records_a), approach_a_path.name)

    raw_b = sorted(_load_jsonl(approach_b_path), key=lambda r: r.get("idx", 0))
    records_b = [_normalise_record(r, "ner_tags", "predicted_tags") for r in raw_b]
    logger.info("Loaded %d Approach B records from %s", len(records_b), approach_b_path.name)

    return records_a, records_b


# Span extraction
def _norm_tag(tag: int | str) -> str:
    if isinstance(tag, int):
        return _INT_TO_BIO.get(tag, "O")
    return str(tag)


def extract_spans(tags: list[int | str]) -> list[tuple[int, int, str]]:
    """Extract entity spans from a BIO tag sequence.

    Supports both integer IDs (0-4) and string BIO tags.

    Returns
    -------
    list of (start, end_exclusive, label) where label is "PER" or "EMAIL".
    """
    spans: list[tuple[int, int, str]] = []
    i, n = 0, len(tags)
    while i < n:
        t = _norm_tag(tags[i])
        if t.startswith("B-"):
            label = t[2:]
            j = i + 1
            while j < n and _norm_tag(tags[j]) == f"I-{label}":
                j += 1
            spans.append((i, j, label))
            i = j
        else:
            i += 1
    return spans


# Bucketing
def compute_buckets(records: list[dict]) -> BucketResult:
    """Count FN/FP errors per entity type across all records."""
    fn_per = fn_email = fp_per = fp_email = 0

    for r in records:
        gold_tags = r.get("gold_tags", [])
        pred_tags = r.get("pred_tags", [])
        n = len(gold_tags)
        pred_aligned = (list(pred_tags) + ["O"] * n)[:n]

        gold_set = set(extract_spans(gold_tags))
        pred_set = set(extract_spans(pred_aligned))

        for span in gold_set - pred_set:
            if span[2] == "PER":
                fn_per += 1
            else:
                fn_email += 1

        for span in pred_set - gold_set:
            if span[2] == "PER":
                fp_per += 1
            else:
                fp_email += 1

    return BucketResult(
        FN_PER=fn_per,
        FN_EMAIL=fn_email,
        FP_PER=fp_per,
        FP_EMAIL=fp_email,
    )


# Error instance collection
def _span_text(tokens: list[str], span: tuple[int, int, str]) -> str:
    return " ".join(tokens[span[0] : span[1]])


def collect_error_instances(records: list[dict]) -> dict[str, list[ErrorInstance]]:
    """Collect every individual error instance, grouped by bucket key."""
    buckets: dict[str, list[ErrorInstance]] = {k: [] for k in BUCKET_KEYS}

    for sent_idx, r in enumerate(records):
        tokens    = r.get("tokens", [])
        gold_tags = r.get("gold_tags", [])
        pred_tags = r.get("pred_tags", [])
        n = len(gold_tags)
        pred_aligned = (list(pred_tags) + ["O"] * n)[:n]

        gold_set = set(extract_spans(gold_tags))
        pred_set = set(extract_spans(pred_aligned))

        for span in gold_set - pred_set:
            key = "FN_PER" if span[2] == "PER" else "FN_EMAIL"
            buckets[key].append(
                ErrorInstance(
                    sentence_idx=sent_idx,
                    tokens=tokens,
                    error_type=key,
                    gold_span=_span_text(tokens, span),
                    pred_span="",
                )
            )

        for span in pred_set - gold_set:
            key = "FP_PER" if span[2] == "PER" else "FP_EMAIL"
            buckets[key].append(
                ErrorInstance(
                    sentence_idx=sent_idx,
                    tokens=tokens,
                    error_type=key,
                    gold_span="",
                    pred_span=_span_text(tokens, span),
                )
            )

    return buckets


# Stratified sampling
def stratified_sample(
    instances: dict[str, list[ErrorInstance]],
    max_total: int = 30,
    seed: int = 42,
) -> list[ErrorInstance]:
    """Sample up to *max_total* errors, proportional to bucket sizes.

    Guarantees at least one sample per non-empty bucket.  Scales down
    proportionally if the total would exceed *max_total*.
    """
    rng = random.Random(seed)
    non_empty = {k: v for k, v in instances.items() if v}
    if not non_empty:
        return []

    total_pool = sum(len(v) for v in non_empty.values())
    quota: dict[str, int] = {
        k: max(1, round(len(v) / total_pool * max_total))
        for k, v in non_empty.items()
    }

    # Trim to budget by reducing the largest bucket iteratively
    while sum(quota.values()) > max_total:
        largest = max(quota, key=lambda k: quota[k])
        if quota[largest] <= 1:
            break
        quota[largest] -= 1

    sampled: list[ErrorInstance] = []
    for key, items in non_empty.items():
        n = min(quota[key], len(items))
        sampled.extend(rng.sample(items, n))

    return sampled


# TSV export
def build_tsv_rows(samples: list[ErrorInstance], approach_label: str) -> list[dict]:
    """Convert sampled error instances to annotation-ready TSV rows."""
    return [
        {
            "approach":     approach_label,
            "sentence_idx": item["sentence_idx"],
            "tokens":       " ".join(str(t) for t in item["tokens"]),
            "error_type":   item["error_type"],
            "gold_span":    item["gold_span"],
            "pred_span":    item["pred_span"],
            "sub_label":    "MANUAL_TODO",
            "notes":        "",
        }
        for item in samples
    ]


def save_tsv(rows: list[dict], path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(TSV_FIELDS), delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)
    logger.info("Saved %d rows -> %s", len(rows), path)


# Plotting
def plot_error_distribution(
    buckets_a: BucketResult,
    buckets_b: BucketResult,
    out_path: pathlib.Path,
    dpi: int = 150,
):
    """Produce a grouped bar chart comparing error buckets for both approaches.

    Returns the matplotlib Figure so callers (e.g. notebooks) can display it
    inline.  Saves a PNG to *out_path* as a side-effect.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError("matplotlib is required: pip install matplotlib") from exc

    counts_a = [getattr(buckets_a, k) for k in BUCKET_KEYS]
    counts_b = [getattr(buckets_b, k) for k in BUCKET_KEYS]
    x = list(range(len(BUCKET_KEYS)))
    w = 0.35

    fig, ax = plt.subplots(figsize=(8, 5))

    bars_a = ax.bar(
        [i - w / 2 for i in x], counts_a, width=w,
        color="#4C72B0", label="Approach A - DeBERTa-v3-small", zorder=3,
    )
    bars_b = ax.bar(
        [i + w / 2 for i in x], counts_b, width=w,
        color="#DD8452", label="Approach B - LLaMA 3.2-1B", zorder=3,
    )

    y_ceil = max(max(counts_a), max(counts_b), 1)
    label_pad = y_ceil * 0.012
    for bar in (*bars_a, *bars_b):
        h = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            h + label_pad,
            f"{int(h):,}",
            ha="center", va="bottom", fontsize=8.5,
        )

    ax.set_xticks(x)
    ax.set_xticklabels(BUCKET_KEYS, fontsize=11)
    ax.set_xlabel("Error Bucket", fontsize=12)
    ax.set_ylabel("Count", fontsize=12)
    ax.set_title("Error Distribution by Bucket and Approach", fontsize=13, pad=12)
    ax.legend(fontsize=10, framealpha=0.9)
    ax.yaxis.grid(True, color="#e0e0e0", linewidth=0.8, zorder=0)
    ax.xaxis.grid(False)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    logger.info("Figure saved -> %s", out_path)
    return fig


# Convenience summary helpers
def summary_table_str(buckets_a: BucketResult, buckets_b: BucketResult) -> str:
    """Return a formatted ASCII summary table for stdout / logging."""
    header = f"{'Bucket':<12}  {'Approach A':>10}  {'A %':>7}  {'Approach B':>10}  {'B %':>7}"
    sep = "-" * len(header)
    lines = [header, sep]
    pct_a, pct_b = buckets_a.pct, buckets_b.pct
    for k in BUCKET_KEYS:
        lines.append(
            f"{k:<12}  {getattr(buckets_a, k):>10,}  {pct_a[k]:>6.1f}%"
            f"  {getattr(buckets_b, k):>10,}  {pct_b[k]:>6.1f}%"
        )
    lines += [
        sep,
        f"{'TOTAL':<12}  {buckets_a.total_errors:>10,}  {'':>7}  {buckets_b.total_errors:>10,}",
    ]
    return "\n".join(lines)


def markdown_table_str(buckets_a: BucketResult, buckets_b: BucketResult) -> str:
    """Return a GitHub-flavoured markdown table of bucket counts."""
    rows = [
        "| Bucket   | Approach A | % A    | Approach B |  % B   |",
        "|----------|------------|--------|------------|--------|",
    ]
    pct_a, pct_b = buckets_a.pct, buckets_b.pct
    for k in BUCKET_KEYS:
        rows.append(
            f"| {k:<8} | {getattr(buckets_a, k):>10,} | {pct_a[k]:>5.1f}% "
            f"| {getattr(buckets_b, k):>10,} | {pct_b[k]:>5.1f}% |"
        )
    rows.append(
        f"| {'**TOTAL**':<8} | {buckets_a.total_errors:>10,} | {'':>6} "
        f"| {buckets_b.total_errors:>10,} | {'':>6} |"
    )
    return "\n".join(rows)


def sample_distribution_str(
    approach: str,
    instances: dict[str, list[ErrorInstance]],
    samples: list[ErrorInstance],
) -> str:
    counts = Counter(s["error_type"] for s in samples)
    total_pool = sum(len(v) for v in instances.values())
    lines = [
        f"{approach}  pool: {total_pool:,} errors  sampled: {len(samples)}",
        f"  {'Bucket':<12}  {'Pool':>6}  {'Sampled':>8}",
    ]
    for k in BUCKET_KEYS:
        lines.append(f"  {k:<12}  {len(instances.get(k, [])):>6,}  {counts.get(k, 0):>8}")
    return "\n".join(lines)
